### ISSUE TITLE
Gradle plugin

### ISSUE THREAD

**Issue by lubo** [Trikke/android-sqlite-generator#5]
Hello, could you make a gradle plugin for this generator ? I would really like to use this generator in one of my projects, yet I am not really willing to manage all the resources it creates on my own, that is what are gradle plugins for.

**Comment by Trikke** [comment]
Hi,

i haven't maintained this project in years as can see from commit logs. It is mainly here so people can fork from or learn from. You are more then welcome to create a gradle plugin for it and send a push request so other people might benefit from it as well.
